# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('module', '0004_auto_20160301_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_object_id', models.PositiveIntegerField()),
                ('material_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='books',
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='modules',
            field=models.ManyToManyField(to='module.Module'),
        ),
    ]
