# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latexbook', '0005_auto_20160316_2309'),
        ('latexbook', '0003_auto_20160313_2048'),
    ]

    operations = [
    ]
