# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameluser',
            name='identifier',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
