# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkquiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechoiceanswer',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='singlechoiceanswer',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
