# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latexbook', '0008_auto_20160329_2240'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeworkquiz', '0002_auto_20160331_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_date', models.DateTimeField()),
                ('node', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='latexbook.BookNode')),
            ],
        ),
        migrations.CreateModel(
            name='MultiChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('save_date', models.DateTimeField(auto_now=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('answer', models.CharField(max_length=200)),
                ('node', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='latexbook.BookNode')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
