# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkquiz', '0004_auto_20160404_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='node',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='latexbook.BookNode'),
        ),
    ]
